using BudgetBeacon.Core.Entities;
using BudgetBeacon.Core.Models;

namespace BudgetBeacon.Infrastructure.Data;

public static class DevelopmentSeedTransactionFactory
{
    private const string FingerprintPrefix = "bb-dev-v1";
    private const string SeedNote = "Generated by the development seed.";

    public static IReadOnlyList<Transaction> CreateTransactions(string userId, DateTime utcNow)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(userId);

        var seedDate = utcNow.Kind == DateTimeKind.Utc
            ? utcNow.Date
            : utcNow.ToUniversalTime().Date;
        var currentMonth = new DateTime(
            seedDate.Year,
            seedDate.Month,
            1,
            0,
            0,
            0,
            DateTimeKind.Utc);
        var transactions = new List<Transaction>();

        for (var offsetFromCurrent = 11; offsetFromCurrent >= 0; offsetFromCurrent--)
        {
            var month = currentMonth.AddMonths(-offsetFromCurrent);
            var salaryVariation = (11 - offsetFromCurrent) % 3 * 75m;
            var utilityVariation = offsetFromCurrent % 4 * 6m;
            var groceryVariation = offsetFromCurrent % 5 * 4m;

            Add(
                transactions,
                userId,
                seedDate,
                month,
                offsetFromCurrent,
                "salary",
                preferredDay: 1,
                3_100m + salaryVariation,
                "Income",
                TransactionTreatment.Income,
                "Monthly salary");
            Add(
                transactions,
                userId,
                seedDate,
                month,
                offsetFromCurrent,
                "rent",
                preferredDay: 2,
                -1_050m,
                "Housing & Utilities",
                TransactionTreatment.Expense,
                "Apartment rent");
            Add(
                transactions,
                userId,
                seedDate,
                month,
                offsetFromCurrent,
                "utilities",
                preferredDay: 5,
                -90m - utilityVariation,
                "Housing & Utilities",
                TransactionTreatment.Expense,
                "Electricity and heating");
            Add(
                transactions,
                userId,
                seedDate,
                month,
                offsetFromCurrent,
                "groceries",
                preferredDay: 8,
                -210m - groceryVariation,
                "Food & Groceries",
                TransactionTreatment.Expense,
                "Local supermarket");
            Add(
                transactions,
                userId,
                seedDate,
                month,
                offsetFromCurrent,
                "restaurant",
                preferredDay: 11,
                -68m - groceryVariation,
                "Eating Out",
                TransactionTreatment.Expense,
                "Restaurant and coffee");
            Add(
                transactions,
                userId,
                seedDate,
                month,
                offsetFromCurrent,
                "transport",
                preferredDay: 12,
                -49m,
                "Transport",
                TransactionTreatment.Expense,
                "Monthly public transport pass");
            Add(
                transactions,
                userId,
                seedDate,
                month,
                offsetFromCurrent,
                "streaming",
                preferredDay: 14,
                -12.99m,
                "Subscriptions & Services",
                TransactionTreatment.Expense,
                "Video streaming subscription");
            Add(
                transactions,
                userId,
                seedDate,
                month,
                offsetFromCurrent,
                "investment",
                preferredDay: 16,
                -400m,
                "Savings & Investments",
                TransactionTreatment.SavingsInvestment,
                "Monthly index fund contribution");
            Add(
                transactions,
                userId,
                seedDate,
                month,
                offsetFromCurrent,
                "transfer",
                preferredDay: 18,
                -250m,
                "Transfers & Adjustments",
                TransactionTreatment.InternalTransfer,
                "Transfer between own accounts");

            AddIrregularTransactions(
                transactions,
                userId,
                seedDate,
                month,
                offsetFromCurrent);
        }

        return transactions;
    }

    private static void AddIrregularTransactions(
        ICollection<Transaction> transactions,
        string userId,
        DateTime seedDate,
        DateTime month,
        int offsetFromCurrent)
    {
        switch (offsetFromCurrent)
        {
            case 1:
                Add(
                    transactions,
                    userId,
                    seedDate,
                    month,
                    offsetFromCurrent,
                    "refund",
                    preferredDay: 20,
                    35m,
                    "Shopping & Personal",
                    TransactionTreatment.Refund,
                    "Returned purchase refund");
                break;
            case 2:
                Add(
                    transactions,
                    userId,
                    seedDate,
                    month,
                    offsetFromCurrent,
                    "shopping",
                    preferredDay: 22,
                    -340m,
                    "Shopping & Personal",
                    TransactionTreatment.Expense,
                    "Seasonal clothing purchase");
                break;
            case 4:
                Add(
                    transactions,
                    userId,
                    seedDate,
                    month,
                    offsetFromCurrent,
                    "adjustment",
                    preferredDay: 10,
                    -15m,
                    "Transfers & Adjustments",
                    TransactionTreatment.Adjustment,
                    "Bank balance correction");
                break;
            case 5:
                Add(
                    transactions,
                    userId,
                    seedDate,
                    month,
                    offsetFromCurrent,
                    "health",
                    preferredDay: 19,
                    -220m,
                    "Health & Insurance",
                    TransactionTreatment.Expense,
                    "Dental appointment");
                break;
            case 7:
                Add(
                    transactions,
                    userId,
                    seedDate,
                    month,
                    offsetFromCurrent,
                    "travel",
                    preferredDay: 21,
                    -480m,
                    "Travel",
                    TransactionTreatment.Expense,
                    "Weekend trip");
                break;
            case 9:
                Add(
                    transactions,
                    userId,
                    seedDate,
                    month,
                    offsetFromCurrent,
                    "leisure",
                    preferredDay: 17,
                    -130m,
                    "Leisure & Hobbies",
                    TransactionTreatment.Expense,
                    "Sports equipment");
                break;
        }
    }

    private static void Add(
        ICollection<Transaction> transactions,
        string userId,
        DateTime seedDate,
        DateTime month,
        int offsetFromCurrent,
        string key,
        int preferredDay,
        decimal amount,
        string category,
        string treatment,
        string description)
    {
        var date = new DateTime(
            month.Year,
            month.Month,
            Math.Min(preferredDay, DateTime.DaysInMonth(month.Year, month.Month)),
            0,
            0,
            0,
            DateTimeKind.Utc);

        if (date > seedDate)
        {
            date = seedDate;
        }

        transactions.Add(new Transaction
        {
            UserId = userId,
            Date = date,
            Amount = amount,
            Category = category,
            Treatment = treatment,
            Notes = SeedNote,
            ImportFingerprint = $"{FingerprintPrefix}:m{offsetFromCurrent:D2}:{key}",
            Metadata = new TransactionMetadata
            {
                RawDescription = description
            }
        });
    }
}
