// <auto-generated />
using BudgetBeacon.Infrastructure.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace BudgetBeacon.Infrastructure.Data.Migrations
{
    [DbContext(typeof(BudgetBeaconDbContext))]
    partial class AddTransactionTreatment
    {
    }
}
